[package]
name = "invaders"
version = "0.1.0"
authors = ["Vladimir Belishov <belyash@seznam.cz>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.1"
rusty_audio = "1.4.0"
rusty_time = "0.12.0"
